### ISSUE TITLE
Support for shouldShowRequestRationale

### ISSUE THREAD

**Issue by ForceGT** [PatilShreyas/permission-flow-android#24]
I was wondering if we can add support for `shouldShowRequestRationale` as mentioned in the recommend flow of permissions by Google

Infact, I was trying to do the same, but I am not too sure about the implementation

**Comment by PatilShreyas** [comment]
@ForceGT I believe that we should acquire this information from the UI layer itself. i.e. from activity/fragment/composable itself

**Comment by ForceGT** [comment]
I agree on that, and that is probably where my confusion is
How do we get an `Activity` from a `Composable`?, as far as I know, each app starts with a `ComponentActivity` but down inside you don't really know if the `Context` can give you an `Activity` instance

**Comment by PatilShreyas** [comment]
For that, you can create a utility for getting `Activity` in compose, like this ⬇️ 

```kt
fun Context.findActivity(): Activity {
    var context = this
    while (context is ContextWrapper) {
        if (context is Activity) return context
        context = context.baseContext
    }
    throw IllegalStateException("Unable to retrieve Activity from the current context")
}
```

**Comment by PatilShreyas** [comment]
Closing this issue, since it's not required. Feel free to discuss though.
