### ISSUE TITLE
Use AppStartup library for auto initialization

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/permission-flow-android#38]

**Comment by yveskalume** [comment]
I'd like to work on this, can I have more explanation about the issue ?

**Comment by PatilShreyas** [comment]
@yveskalume Thanks for showing interest, but it's already WIP here: https://github.com/PatilShreyas/permission-flow-android/pull/20

**Comment by PatilShreyas** [comment]
This has been released in `v1.1.0`
