### ISSUE TITLE
Getting Fragment not attached to an activity exception

### ISSUE THREAD

**Issue by daniel-waiguru** [PatilShreyas/permission-flow-android#54]
I'm trying to use the library version 1.1.0 in a Fragment but I get a crash with 
`Caused by: java.lang.IllegalStateException: Fragment XYZ{8954ecf} (8e69d028-83c3-4c49-90fb-7e0e59a8156a) not attached to an activity.`

What is have done

1. added lib dependency

2. obtained ActivityResultLauncher in my Fragment as below

`private val permissionLauncher = registerForPermissionFlowRequestsResult()`

3. Ran my project and got the crash

Am I missing something?

**Comment by PatilShreyas** [comment]
Thanks @daniel-waiguru for raising this issue. This seems like a library issue. Will get it fixed in the upcoming version

**Comment by PatilShreyas** [comment]
This has been fixed and released in v`1.2.0`
