### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Kranthi94** [PatilShreyas/permission-flow-android#63]
Getting Package not found when requesting for permissions. Checked on API Level 31 and 32. Attaching Log Screenshot
![Screenshot 2023-07-05 at 4 01 00 PM](https://github.com/PatilShreyas/permission-flow-android/assets/13165950/75fc17f6-51e1-4fcc-b624-b81aff49d193)

**Comment by PatilShreyas** [comment]
Can you share a sample?
