### ISSUE TITLE
No support for rational dialog after user denies permission more than once

### ISSUE THREAD

**Issue by hirenrafaliya** [PatilShreyas/permission-flow-android#76]
If user denies a permission more than once than we can't ask for that again. Instead we need to show user about the need of permission for that feature and navigate users to settings page to manually grant the permission.

**Comment by niranjandawadi** [comment]
This issue needs to be fixed. When the user declines permission more than once there is no option for users to redirect to the settings page.

**Comment by PatilShreyas** [comment]
The support for rationale has been added in v`2.0.0`
