### ISSUE TITLE
Wrong state for Manifest.permission.ACCESS_NOTIFICATION_POLICY

### ISSUE THREAD

**Issue by Sypers** [PatilShreyas/permission-flow-android#78]
Hello, i've been using this library to handle permissions in my app. And i've noticed that it works fine with other permissions in my app except this one (Manifest.permission.ACCESS_NOTIFICATION_POLICY). for some reason the state of this permission isGranted value is **always true even when the permission is not granted**. i have tried it on multiple emulator instances and my physical device and all have produced the same results. Unfortunately i don't have much knowledge in this library except on how to use it, and i don't know what causes this or how to solve it.

**Comment by PatilShreyas** [comment]
@Sypers thanks for raising the issue. How does it behave when you use core permission API?
```
ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_NOTIFICATION_POLICY)
```

**Comment by Sypers** [comment]
> @Sypers thanks for raising the issue. How does it behave when you use core permission API?
> 
> ```
> ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_NOTIFICATION_POLICY)
> ```

Yes, even though the permission is not granted it returns `PackageManager.PERMISSION_GRANTED`

**Comment by Sypers** [comment]
I noticed that using `NotificationManager.isNotificationPolicyAccessGranted` returns the correct value.
