### ISSUE TITLE
isRationaleRequired is null after manual initialization

### ISSUE THREAD

**Issue by polodarb** [PatilShreyas/permission-flow-android#92]
Hi, when adding WorkManager (Including the initializer in the manifest):

```
<provider
   android:name="androidx.startup.InitializationProvider"
   android:authorities="${applicationId}.androidx-startup"
   tools:node="remove" />
```

An error occurs:
```
java.lang.IllegalStateException: Failed to create instance of PermissionFlow. Did you forget to call PermissionFlow.init(context)?
 ```

But after adding the [PermissionFlow initializer](https://github.com/PatilShreyas/permission-flow-android#6-what-about-initialization) to the Aplication class and manifest - the value of `isRationaleRequired` becomes null:
```
permission=android.permission.POST_NOTIFICATIONS, isGranted=false, isRationaleRequired=null)
```

Maybe it's some kind of mistake on my part?

**Comment by PatilShreyas** [comment]
@polodarb After initializing it, are you also calling `startListening`?

**Comment by polodarb** [comment]
No, but i fixed it in Manifest via `tools:node="merge"`. Thanks!

**Comment by polodarb** [comment]
Oh, no, I'm sorry. That didn't fix the problem, now WorkManager is not working 😅
